spring:
  application:
    name: ${APPLICATION_NAME:readapi}
  datasource:
    url: jdbc:mysql://localhost:3306/footballobzor
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Defaults to "none" when NOT in embedded mode
server.port: 8081
liquibase:
  change-log: liquibase-changeLog.xml

amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAICEGHM4IRTUTLDMQ
  secretKey: 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
  bucketName: footballobzor
